version: '3.8'

services:
  app:
    build: .
    container_name: node_app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "9394:9394"
    environment:
      - NODE_ENV=development
    command: npm run dev
